name: Daily Fund Analyst

on:
  schedule:
    # 每天北京时间 10:00 (UTC 02:00) 运行，增加备份时间点
    # UTC 02:00 = 北京时间 10:00
    # UTC 03:00 = 北京时间 11:00
    # UTC 04:00 = 北京时间 12:00
    - cron: '0 2 * * *'
    - cron: '0 3 * * *'
    - cron: '0 4 * * *'
  workflow_dispatch: # 允许手动点击按钮运行

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # 强制更新 akshare 确保金融接口可用
        pip install --upgrade akshare
        pip install -r requirements.txt

    - name: Run Analysis
      env:
        # === Secrets ===
        LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
        LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}
        TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        
        # === Variables ===
        ETF_LIST: ${{ vars.ETF_LIST }}
        MUTUAL_LIST: ${{ vars.MUTUAL_LIST }}
        LLM_MODEL: ${{ vars.LLM_MODEL }}
      run: |
        python main.py
